### ISSUE TITLE
polyline component adds material property, error occurs

### ISSUE THREAD

**Issue by computeone** [reearth/resium#602]
```
import { Cartesian3, Color, Material, Transforms } from 'cesium';
import { CameraFlyTo, Polyline, PolylineCollection, Viewer } from 'resium';

export const Scene3D: React.FC = (): JSX.Element => {
    const center = Cartesian3.fromDegrees(-75.59777, 40.03883);
    const positions = [new Cartesian3(-75, 35, 0), new Cartesian3(-125, 35, 0), new Cartesian3(-125, 135, 0)];
    return (
        <Viewer full>
            <PolylineCollection modelMatrix={Transforms.eastNorthUpToFixedFrame(center)}>
                <Polyline
                    positions={positions}
                    material={Material.fromType(Material.ColorType, {
                        color: new Color(1, 0, 0, 1),
                    })}
                />
            </PolylineCollection>
            <CameraFlyTo duration={0} destination={Cartesian3.fromDegrees(-75.6, 40.04, 1000)} />
        </Viewer>
    );
};
```

```
DeveloperError: This object was destroyed, i.e., destroy() was called.

Error
    at new DeveloperError (http://localhost:3000/cesium/Cesium.js:12583:13)
    at Material.throwOnDestroyed (http://localhost:3000/cesium/Cesium.js:28943:13)
    at createCommandLists (http://localhost:3000/cesium/Cesium.js:117007:29)
    at PolylineCollection.update (http://localhost:3000/cesium/Cesium.js:116937:7)
    at PrimitiveCollection.update (http://localhost:3000/cesium/Cesium.js:150713:22)
    at updateAndRenderPrimitives (http://localhost:3000/cesium/Cesium.js:212549:23)
    at executeCommandsInViewport (http://localhost:3000/cesium/Cesium.js:212401:5)
    at Scene4.updateAndExecuteCommands (http://localhost:3000/cesium/Cesium.js:212219:7)
    at render (http://localhost:3000/cesium/Cesium.js:212855:11)
    at tryAndCatchError (http://localhost:3000/cesium/Cesium.js:212869:7)
```

**Comment by rot1024** [comment]
How about this?

```js
const material = useMemo(() => Material.fromType(Material.ColorType, { ... });

// ...

<Polyline material={material} />
```

**Comment by computeone** [comment]
This will still report an error because the material was destroyed when destorying

**Comment by computeone** [comment]
using useMemo doesn't work, it still reports an error

**Comment by computeone** [comment]
This is a bug not a question！

**Comment by eksant** [comment]
Any update for this issue ?
I have same error like screenshot below:
![image](https://github.com/reearth/resium/assets/32409305/a68289be-80e1-4bcf-9619-bba48774371b)
![image](https://github.com/reearth/resium/assets/32409305/7dfe5992-57b9-48a5-88c1-ba1e09cb344b)

**Comment by benwiles1** [comment]
@eksant the material prop is expecting a 'Material' not a 'MaterialProperty`. that is a regular type error, is correct, and is unrelated to this issue

**Comment by benwiles1** [comment]
this bug specifically appears when using React StrictMode because the material property is destroyed and reused in a single render due to StrictMode's unmount + remount logic to detect non-declarative components.

So it seems that `Polyline` is just broken because unmounting it modifies the passed in material prop.
I'd also be suspicious of any other components that takes destroyable props.
This can be worked around by not using StrictMode and being very careful about renders, but I'm concerned that this will unexpectedly break again at any moment.

**Comment by rot1024** [comment]
Fixed in #780 (merged to main).
