### ISSUE TITLE
Trying to open index.html from build

### ISSUE THREAD

**Issue by endureairShivam** [reearth/resium#653]
I am trying to open index.html from build of the app and it is not showing anything and giving different errors in console.log .

**Comment by endureairShivam** [comment]
Error I am facing:
SecurityError: Failed to execute 'texImage2D' on 'WebGL2RenderingContext': The image element contains cross-origin data, and may not be loaded.

Error: Failed to execute 'texImage2D' on 'WebGL2RenderingContext': The image element contains cross-origin data, and may not be loaded.
    at new pm (file:///C:/Users/Shivam%20Arora/reactlog/example/build/cesium/Cesium.js:3854:5297)
    at He.update (file:///C:/Users/Shivam%20Arora/reactlog/example/build/cesium/Cesium.js:4581:1587)
    at sD.update (file:///C:/Users/Shivam%20Arora/reactlog/example/build/cesium/Cesium.js:11747:173673)
    at Rw.update (file:///C:/Users/Shivam%20Arora/reactlog/example/build/cesium/Cesium.js:11747:176923)
    at ui.updateEnvironment (file:///C:/Users/Shivam%20Arora/reactlog/example/build/cesium/Cesium.js:14612:29471)
    at S0t (file:///C:/Users/Shivam%20Arora/reactlog/example/build/cesium/Cesium.js:14612:38897)
    at YT (file:///C:/Users/Shivam%20Arora/reactlog/example/build/cesium/Cesium.js:14612:39117)
    at ui.render (file:///C:/Users/Shivam%20Arora/reactlog/example/build/cesium/Cesium.js:14612:40145)
    at OT.render (file:///C:/Users/Shivam%20Arora/reactlog/example/build/cesium/Cesium.js:14614:1631)
    at n (file:///C:/Users/Shivam%20Arora/reactlog/example/build/cesium/Cesium.js:14612:54821)

**Comment by rot1024** [comment]
The `texImage2D` / cross-origin error here comes from opening the built `index.html` directly via `file://`, which is a CesiumJS/WebGL cross-origin limitation rather than a Resium issue — the app needs to be served over HTTP(S). For more on this please see the Cesium community at https://community.cesium.com/ . Closing here, thanks!
